import { CoinbaseProduct } from "../types";

export const mockCoins: CoinbaseProduct[] = [
  {
    product_id: "BTC-USD",
    price: "93078",
    price_percentage_change_24h: "-2.32921700410577",
    volume_24h: "5735.17446988",
    volume_percentage_change_24h: "256.29581697256864",
    base_increment: "0.00000001",
    quote_increment: "0.01",
    quote_min_size: "1",
    quote_max_size: "150000000",
    base_min_size: "0.00000001",
    base_max_size: "3400",
    base_name: "Bitcoin",
    quote_name: "US Dollar",
    watched: false,
    is_disabled: false,
    new: false,
    status: "online",
    cancel_only: false,
    limit_only: false,
    post_only: false,
    trading_disabled: false,
    auction_mode: false,
    product_type: "SPOT",
    quote_currency_id: "USD",
    base_currency_id: "BTC",
    fcm_trading_session_details: null,
    mid_market_price: "",
    alias: "",
    alias_to: ["BTC-USDC"],
    base_display_symbol: "BTC",
    quote_display_symbol: "USD",
    view_only: false,
    price_increment: "0.01",
    display_name: "BTC-USD",
    product_venue: "CBE",
    approximate_quote_24h_volume: "533818569.31",
    new_at: "2023-01-01T00:00:00Z",
    market_cap: "",
    base_cbrn: "",
    quote_cbrn: "",
    product_cbrn: "",
    icon_color: "",
    icon_url: "",
    display_name_overwrite: "",
    is_alpha_testing: false,
    about_description: "",
    price_difference: "0",
    price_difference_percent: "0",
    side: "buy",
  },
  {
    product_id: "ETH-USD",
    price: "3215.24",
    price_percentage_change_24h: "-3.7845893270212",
    volume_24h: "83035.63491226",
    volume_percentage_change_24h: "221.33879191043552",
    base_increment: "0.00000001",
    quote_increment: "0.01",
    quote_min_size: "1",
    quote_max_size: "150000000",
    base_min_size: "0.00000001",
    base_max_size: "42000",
    base_name: "Ethereum",
    quote_name: "US Dollar",
    watched: false,
    is_disabled: false,
    new: false,
    status: "online",
    cancel_only: false,
    limit_only: false,
    post_only: false,
    trading_disabled: false,
    auction_mode: false,
    product_type: "SPOT",
    quote_currency_id: "USD",
    base_currency_id: "ETH",
    fcm_trading_session_details: null,
    mid_market_price: "",
    alias: "",
    alias_to: ["ETH-USDC"],
    base_display_symbol: "ETH",
    quote_display_symbol: "USD",
    view_only: false,
    price_increment: "0.01",
    display_name: "ETH-USD",
    product_venue: "CBE",
    approximate_quote_24h_volume: "266979494.8",
    new_at: "2023-01-01T00:00:00Z",
    market_cap: "",
    base_cbrn: "",
    quote_cbrn: "",
    product_cbrn: "",
    icon_color: "",
    icon_url: "",
    display_name_overwrite: "",
    is_alpha_testing: false,
    about_description: "",
    price_difference: "0",
    price_difference_percent: "0",
    side: "buy",
  },
];
